### ISSUE TITLE
Not Working in Ubuntu

### ISSUE THREAD

**Issue by KevinWFinMin** [instructure/canvas-data-cli#13]
When I try to install the Canvas-Data-Cli it tells me this: 

> npm WARN chai-fs@0.1.0 requires a peer of chai@>= 1.6.1 < 2 but none is installed. You must install peer dependencies yourself.

Then if I try to run it from the command line I get this:

canvasDataCli
module.js:538
    throw err;
    ^

Error: Cannot find module './lib/Api'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/canvas-data-cli/index.js:2:8)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)

Can anyone tell me what's going on? I have it working fine on Windows 10.

**Comment by KevinWFinMin** [comment]
Even after installing the proper version of Chai I'm still getting the same error. 


$ npm install -g chai@1.6.1
**+ chai@1.6.1
removed 3 packages and updated 1 package in 0.366s**
$ npm install -g canvas-data-cli
**/usr/bin/canvasDataCli -> /usr/lib/node_modules/canvas-data-cli/bin/canvasDataCli
npm WARN chai-fs@0.1.0 requires a peer of chai@>= 1.6.1 < 2 but none is installed. You must install peer dependencies yourself.**

+ canvas-data-cli@0.6.0
updated 1 package in 1.23s

**Comment by wbuchanan** [comment]
If you install the version recommended in the documentation:

```
npm install -g canvas-data-cli@0.5.4
```

You shouldn't get the error you received above.  However, you my get the same error that I encountered and submitted in issue #15
