### ISSUE TITLE
unpack error

### ISSUE THREAD

**Issue by catkins6** [instructure/canvas-data-cli#2]
Hi Addison,

I was able to successfully sync using the canvas-data-cli but I am receiving an error when using the unpack. It creates the text file with headers but the data is not included. I have received two different errors but the results are still the same.

canvasDataCli -c config.js unpack -f account_dim
outputting account_dim to /Users/catkins/Sites/candata/unpackedFiles/account_dim.txt
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: unknown compression method
    at Zlib._handle.onerror (zlib.js:363:17)

canvasDataCli -c config.js unpack -f enrollment_dim
outputting enrollment_dim to /Users/catkins/Sites/candata/unpackedFiles/enrollment_dim.txt
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: incorrect header check
    at Zlib._handle.onerror (zlib.js:363:17)

**Comment by SecurityInsanity** [comment]
:disappointed: Man we really dropped the ball on this one.

As mentioned in #7 we haven't seen this in a long time. Are you still running into this issue after updating the CLI?

**Comment by jagobrown** [comment]
I've just hit this same issue but raised it here: https://github.com/instructure/canvas-data-cli/issues/7
Jago

**Comment by catkins6** [comment]
Thanks for checking in SecurityInsanity I do not remember how but I was able to fix this problem.

**Comment by mcjelewis** [comment]
I am now getting the "Unhandled 'error' event" message. The unpack command works with other tables, but I can't get it to run anymore on the requests data.

----------------------
it-m-mlewis23:canvasDataCli mlewis$ canvasDataCli unpack -c canvas-data-cli/config.js -f requests
outputting requests to [path to file]/requests.txt
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: unknown compression method
    at Zlib._handle.onerror (zlib.js:363:17)
----------------------

Anyone know how this was fixed in the past?

**Comment by mcjelewis** [comment]
After deleting all folders and files from dataFiles (the folder where all gz files are synced to) and rerunning the sync command, I was able to get the requests files to unpack.

**Comment by SecurityInsanity** [comment]
Hey @mcjelewis ,

This can sometimes happen if there's an intermittent network error, or disk error. The CLI doesn't actually verify the downloaded file is the exact same as those being served from S3 (thus ensuring the download completed with no weird faults). So yes if you see this error it probably means that file wasn't downloaded correctly. You should just be able to remove the affected files, and re-run sync (since sync is "smart" in the sense it downloads anything that doesn't exist).

However if you see this for a file across multiple syncs than it is a problem that you should file an issue about, or file a support case for.

**Comment by mcjelewis** [comment]
Thanks for the quick response.

The error came back again on the second sync/unpack process. This time I got it to work by updating node to v9.8. I'm not sure what version I was on previously, but I don't think I had updated in a while.
