### ISSUE TITLE
Max Number of Retries Reached

### ISSUE THREAD

**Issue by venkat5121** [instructure/canvas-data-cli#29]
### Description ###

We use canvas-data-cli to download our files daily at 3:30 pm. This has been our regular process for over a year now.
Starting yesterday, our process is failing with following error:
```
Error: max number of retries reached for submission_dim-00027-3052c8c0.gz, aborting
    at /usr/lib/node_modules/canvas-data-cli/lib/FileDownloader.js:52:18
    at Timeout._onTimeout (/usr/lib/node_modules/canvas-data-cli/node_modules/re/lib/re.js:90:43)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
```
Our process is a combination of the list, grab, fetch, and unpack with some directory creation and removal steps.
Instead of running the process as a whole, I tried to run only grab command to download .gz files of the latest dumpid. The error is consistent. 

I do not know if something needs to be updated in /usr/lib/node_modules directories or some where else, Please help how I can resolve this.

### Additional Information ### 
```
node -v
v14.11.0
npm -v
6.14.8
canvasDataCli -v
0.6.6
RHELinux
uname -r
3.10.0-1127.19.1.el7.x86_64
```
* Logs: attaching log file.

**Comment by venkat5121** [comment]
[
[error20201014.log](https://github.com/instructure/canvas-data-cli/files/5381655/error20201014.log)
](url)

**Comment by baldwin1** [comment]
Any update on this?  I am getting the same error trying to do a fetch on requests - canvasDataCli fetch -c ./config.js -t requests

**Comment by fmurillou** [comment]
Hi, I'm getting the same error doing a sync process.

**Comment by fmurillou** [comment]
Hi, I have solved the error. You can try 3 thing: 1) Increase your machine storage, it's possible you get a high volume of files, 2) upgrade node.js to the last version 3) if you are using Linux, try with windows
