### ISSUE TITLE
fileUrl is not defined

### ISSUE THREAD

**Issue by jmiles2irvine** [instructure/canvas-data-cli#3]
During download, i'm getting an error:

ReferenceError: fileUrl is not defined
    at FileDownloader._downloadRetry (C:\Users\JasonMiles\AppData\Roaming\npm\node_modules\canvas-data-cli\lib\FileDownloader.js:32:94)
    at null._onTimeout (C:\Users\JasonMiles\AppData\Roaming\npm\node_modules\canvas-data-cli\lib\FileDownloader.js:46:26)
    at Timer.listOnTimeout (timers.js:92:15)

**Comment by addisonj** [comment]
Thanks for reporting this! This was occurring due to hitting an error path, which was happening more often due to an underlying bug with pagination.

canvas-data-cli version 0.2.0 was just published and should fix this issue!

Closing this, but feel free to reopen if you still see issues.
