### ISSUE TITLE
Initial Sync fails with request timeout

### ISSUE THREAD

**Issue by wonkie** [instructure/canvas-data-cli#4]
Got everything installed under Windows 10. I set ENV variable but they were not read:

*config at D:\Users\xxxx\Documents\Canvas\Data\config.js is invalid
missing key, secret fields in config*

config settings [as distributed]
  key: process.env.CD_API_KEY, // don't hardcode creds, keep them in environment variables ideally!
  secret: process.env.CD_API_SECRET

so I hard-coded the keys and launched with:
**D:\temp>canvasDataCli sync -c "D:\Users\xxxx\Documents\Canvas\Data\config1.js"**

Started off okay...
*starting from sequence 0
will process 100 dumps
downloading 113 artifacts*

but after a long while (see attached log: [syncLog.txt](https://github.com/instructure/canvas-data-cli/files/141335/syncLog.txt)
) I got this error:
*an error occured
[Error: max number of retries reached for requests-00000-ca7e907b.gz, aborting]
Error: max number of retries reached for requests-00000-ca7e907b.gz, aborting
    at C:\Users\xxxx\AppData\Roaming\npm\node_modules\canvas-data-cli\lib\FileDownloader.js:52:18
    at null._onTimeout (C:\Users\xxxx\AppData\Roaming\npm\node_modules\canvas-data-cli\node_modules\re\lib\re.js:90:43)
    at Timer.listOnTimeout (timers.js:92:15)*

**Comment by addisonj** [comment]
sorry for the issues....

About how long was it till it error'ed? More than 2 hours?

We do have a time limit to when the download links from the API expire, but this generally shouldn't be an issue unless you either have a pretty slow connection or are downloading data for a very large school. 

We have some plans to improve that, but it might be a bit. In the meantime, if you drop a file called `state.json` into the same folder with contents
```JSON
{"sequence": 92}
```

That should start downloading just from sequence 92 (which looks like you have files for 91) and then be on your way.

Let me know on how long it took and if that workaround works!

**Comment by wonkie** [comment]
Thanks for the fast response! I was going to build a similar tool in PowerShell so you've saved me heaps of work.

The initial failure was after about 30 mins. Earlier today, I created the state.json file as you directed, and put it in the same directory as the config (the one with hard-coded keys since I could not get the env variables to read). 

The process worked this time and took about 15 minutes. I can post the full log if you want, but here is the start and end:
```
starting from sequence 0
will process 101 dumps
downloading 114 artifacts
artifact account_dim from dump 101 replaces old files, will delete old files
artifact assignment_dim from dump 101 replaces old files, will delete old files
artifact assignment_fact from dump 101 replaces old files, will delete old files
artifact assignment_group_dim from dump 101 replaces old files, will delete old files
artifact assignment_group_fact from dump 101 replaces old files, will delete old files
artifact account_dim from dump 101 has 1 to download
.... <snip> ...
artifact requests from dump 101 has 1 to download
artifact requests from dump 101 finished
finished, saving out state, newest sequence: 101
sync command completed successfully
```

In the \dataFiles directory I found the 56 directories plus the schema file. Next up: unzip.
I issued the unpack command from the dataFiles directory:
```
D:\temp\dataFiles>canvasDataCli unpack -c D:\Users\xxxx\Documents\Canvas\Data\config1.js -f user_dim,account_dim
could not find schema, have you downloaded files yet?
an error occured
{ [Error: ENOENT: no such file or directory, stat 'D:\temp\dataFiles\dataFiles\schema.json']
  errno: -4058,
  code: 'ENOENT',
  syscall: 'stat',
  path: 'D:\\temp\\dataFiles\\dataFiles\\schema.json' }
Error: ENOENT: no such file or directory, stat 'D:\temp\dataFiles\dataFiles\schema.json'
    at Error (native)
```
based on the last error, I moved up on directory and re-tried:
```
D:\temp>canvasDataCli unpack -c D:\Users\xxxx\Documents\Canvas\Data\config1.js -f user_dim,account_dim
no files matched filter, nothing will be unpacked
unpack command completed successfully
``` 
However, I experimented and found that if I used a *space* instead of a *comma*, it worked:
```
D:\temp>canvasDataCli unpack -c D:\Users\xxxx\Documents\Canvas\Data\config1.js -f assignment_dim assignment_fact
outputting assignment_dim to D:\temp\unpackedFiles\assignment_dim.txt
outputting assignment_fact to D:\temp\unpackedFiles\assignment_fact.txt
```
So, looking good!
