### ISSUE TITLE
The header content contains invalid characters

### ISSUE THREAD

**Issue by lis10** [instructure/canvas-data-cli#5]
When I tried to sync using the command line utility and received a "The header content contains invalid characters" error.

The machine is a Windows 2012 R2 server (virtual machine)
Do you need any additional information? 

.. command line error output

starting from sequence 0
_http_outgoing.js:348
    throw new TypeError('The header content contains invalid characters');
    ^

TypeError: The header content contains invalid characters
    at ClientRequest.OutgoingMessage.setHeader (_http_outgoing.js:348:11)
    at new ClientRequest (_http_client.js:85:14)
    at Object.exports.request (http.js:31:10)
    at Object.exports.request (https.js:197:15)
    at Request.start (C:\Users\lis10\AppData\Roaming\npm\node_modules\canvas-data-cli\node_modules\request\request.js:747:30)
    at Request.end (C:\Users\lis10\AppData\Roaming\npm\node_modules\canvas-data-cli\node_modules\request\request.js:1381:10)
    at end (C:\Users\lis10\AppData\Roaming\npm\node_modules\canvas-data-cli\node_modules\request\request.js:575:14)
    at Immediate._onImmediate (C:\Users\lis10\AppData\Roaming\npm\node_modules\canvas-data-cli\node_modules\request\request.js:589:7)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

**Comment by lis10** [comment]
Working now..
The problem was using Node.js version 5.7 (latest) you have to use version 5.5
This article helped
https://fossies.org/diffs/node/v5.5.0_vs_v5.6.0/lib/_http_outgoing.js-diff.html
