### ISSUE TITLE
incorrect header check - wiki_page_fact

### ISSUE THREAD

**Issue by agschmidt** [instructure/canvas-data-cli#7]
I completed the sync without errors, then tried to unpack all files. There seems to be a problem with the headers of the wiki_page_fact table. All files had the header files, but no data. I reran the unpack command for just a few tables and it worked fine for them.

outputting wiki_page_fact to path\unpackedFiles\wiki_page_fact.txt
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: incorrect header check
    at Zlib._handle.onerror (zlib.js:363:17)

**Comment by SecurityInsanity** [comment]
:disappointed: Sorry about the late reply on this. Are you still running into this? We saw this a long time ago with the CLI, but if you're running the latest version this shouldn't be happening anymore.

**Comment by jagobrown** [comment]
Hello,
canvas-data-cli has been running fine up until now, but am now getting this error:
...
outputting ...
events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: incorrect header check
    at Zlib._handle.onerror (zlib.js:370:17)

# with npm -v 3.10.10 and canvasDataCli --version 0.5.4

has something changed with the schema or other?
Kind regards
Jago

**Comment by SecurityInsanity** [comment]
Hey @jagobrown ,

This wouldn't be an issue with a schema change (although we have release notes now in the community). Can you let us know the command you're running, and provide us with debug logs (you can get these by adding `-l debug` to your command)
